/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package du.an.pkg1;

import helper.dialogHelper;
import helper.shareHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class formchojdialog extends javax.swing.JFrame {

    /**
     * Creates new form formchojdialog
     */
    public formchojdialog() {
        initComponents();
        Hienthi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      void Hienthi() {
       
        setLocationRelativeTo(null);    
    
      
       
        new Timer(1000, new ActionListener() {
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                Lbdongho.setText(sdf.format(new Date()));
            }
        }).start();
       
    }
         public void openX(JInternalFrame x) {
        for (JInternalFrame frmChild : jdestopanel.getAllFrames()) {
            frmChild.dispose();
        }

        x.setLocation(this.getWidth() / 2 - x.getWidth() / 2,
                (this.getHeight() - 20) / 2 - x.getHeight() / 2 - 60);
        jdestopanel.add(x);
        x.setVisible(true);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        destop = new javax.swing.JPanel();
        jdestopanel = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        Lbdongho = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem16.setText("jMenuItem16");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Exit.png")); // NOI18N
        jButton1.setText("Đăng Xuất");
        jPanel1.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Stop.png")); // NOI18N
        jButton3.setText("Kết Thúc");
        jPanel1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Lists.png")); // NOI18N
        jButton4.setText("Chuyên đề");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Conference.png")); // NOI18N
        jButton5.setText("Người học ");
        jPanel1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Certificate.png")); // NOI18N
        jButton6.setText("Khóa học");
        jPanel1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Boy.png")); // NOI18N
        jButton7.setText("Học viên ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Globe.png")); // NOI18N
        jButton8.setText("Hướng dẫn");
        jPanel1.add(jButton8);

        javax.swing.GroupLayout jdestopanelLayout = new javax.swing.GroupLayout(jdestopanel);
        jdestopanel.setLayout(jdestopanelLayout);
        jdestopanelLayout.setHorizontalGroup(
            jdestopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdestopanelLayout.setVerticalGroup(
            jdestopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout destopLayout = new javax.swing.GroupLayout(destop);
        destop.setLayout(destopLayout);
        destopLayout.setHorizontalGroup(
            destopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdestopanel)
        );
        destopLayout.setVerticalGroup(
            destopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destopLayout.createSequentialGroup()
                .addComponent(jdestopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Info.png")); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");

        Lbdongho.setForeground(new java.awt.Color(0, 51, 255));
        Lbdongho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Alarm.png")); // NOI18N
        Lbdongho.setText("00:00");

        jMenu1.setText("Hệ Thống");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Exit.png")); // NOI18N
        jMenuItem2.setText("Đăng Xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Create.png")); // NOI18N
        jMenuItem3.setText("Đổi  mật khẩu");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Stop.png")); // NOI18N
        jMenuItem4.setText("Thoát chương trình ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Conference.png")); // NOI18N
        jMenuItem5.setText("Người học");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Lists.png")); // NOI18N
        jMenuItem6.setText("Chuyên đề");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Certificate.png")); // NOI18N
        jMenuItem7.setText("Khóa học");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\User group.png")); // NOI18N
        jMenuItem9.setText("Quản lý nhân viên");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống Kê");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\List.png")); // NOI18N
        jMenuItem11.setText("Người học từng năm");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Card file.png")); // NOI18N
        jMenuItem12.setText("Bảng điểm khóa");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Bar chart.png")); // NOI18N
        jMenuItem13.setText("Điểm từng khóa");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Dollar.png")); // NOI18N
        jMenuItem14.setText("Doanh thu từng chuyên đề");
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ Giúp");

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Globe.png")); // NOI18N
        jMenuItem15.setText("Hướng dẫn sử dụng");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\duan_ngayxua-master\\duan_ngayxua-master\\Source code\\Du an mau\\src\\icon\\Brick house.png")); // NOI18N
        jMenuItem17.setText("Giới thiệu sản phẩm");
        jMenu4.add(jMenuItem17);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(destop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbdongho, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Lbdongho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
         // TODO add your handling code here:
       new QuanLyNhanVienJInternalFrame().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       int a=JOptionPane.showConfirmDialog(this,"bạn có muốn thoát chương trình không",JOptionPane.OPTIONS_PROPERTY,JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.YES_NO_OPTION) {
            System.exit(0);
            
        }
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed
//    public void openChuyenDe() {
//        if (shareHelper.authenticated()) {
//            QuanLyChuyenDeJInternalFrame abc= new QuanLyChuyenDeJInternalFrame();
//            openX(abc);
//        } else {
//            dialogHelper.alert(this, "Vui lòng đăng nhập!");
//        }
//    }
//      
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

  
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new Quanlychuyende().setVisible(true);
       
    }//GEN-LAST:event_jMenuItem6ActionPerformed
          
  
  
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        new Quanlynguoihoc().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new Quanlykhoahoc().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Quanlyhocvien().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formchojdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formchojdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formchojdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formchojdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formchojdialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbdongho;
    private javax.swing.JPanel destop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdestopanel;
    // End of variables declaration//GEN-END:variables

   
   
}
